x-postgres-env: &postgres-env
  POSTGRES_USER: ampelios
  POSTGRES_PASSWORD: segmenter1
  POSTGRES_DB: ampelios

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: ampelios_postgres
    environment:
      <<: *postgres-env
      POSTGRES_INITDB_ARGS: "--locale=C.UTF-8 --encoding=UTF8"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  ampelios:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: ampelios
    depends_on:
      - postgres
    environment:
      <<: *postgres-env
      POSTGRES_HOST: postgres
      PREFECT_LOGGING_LEVEL: INFO
      PREFECT_LOGGING_SERVER_LEVEL: INFO
    ports:
      - "1032:1032"
    volumes:
      - models_data:/app/models
      - ../init-data:/app/init-data # TODO: create kafka consumer for loading from input
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1032/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
  models_data:
